import Head from "next/head";
import { Container, Typography } from "@mui/material";
import { DetailsCard } from "@/components/DetailsCard";
import { useAppSelector, useAppDispatch } from "@/store/hook";
import { selectTitle } from "@/store/slices/getDetailSlice";
import { useRouter } from "next/router";
import { useEffect } from "react";
import {
  loadMovie,
  selectMovieStatus,
} from "@/store/slices/getDetailSlice";

export default function Details() {
  const Title = useAppSelector(selectTitle);

  const router = useRouter();
  const { status, error } = useAppSelector(selectMovieStatus);
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (status === "idle" && router.query.slug !== undefined) {
      dispatch(loadMovie(router.query.slug as string));
    }
  }, [status, router, dispatch]);

  return (
    <>
      <Head>
        <title>{Title ? Title : "Movie Search"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="md">
          {status === "loading" && <Typography>Loading...</Typography>}
          {error && (
            <Typography>Something go wrong, try it later....</Typography>
          )}
          {status === "received" && <DetailsCard />}
        </Container>
      </main>
    </>
  );
}
