import Head from "next/head";
import { Box, Container, Typography, Grid, Button } from "@mui/material";
import { useAppSelector } from "@/store/hook";
import { MovieCard } from "@/components/MovieCard";
import { useRouter } from "next/router";

export default function Favorite() {
  const favorite = useAppSelector((state) => state.favorite.list);
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Favorite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="lg">
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              minHeight: "75vh",
              my: "15px",
            }}
          >
            <Button
              variant="outlined"
              fullWidth
              onClick={() => {
                router.push("/");
              }}
            >
              Go home
            </Button>
            {favorite.length === 0 ? (
              <Typography>
                You have not added movies to your list yet
              </Typography>
            ) : (
              <Grid container spacing={7} sx={{ my: "15px" }}>
                {favorite.map((movie) => (
                  <MovieCard key={movie.imdbID} movie={movie} favorite />
                ))}
              </Grid>
            )}
          </Box>
        </Container>
      </main>
    </>
  );
}
